"""Build the browser's replay catalog from the bundled, pinned PHH sources."""
import hashlib
import json
from pathlib import Path
import tomllib

ROOT = Path(__file__).resolve().parents[1]
REVISION = "e47fbd5816372360bade4de5d712346fe1bb70f6"


def convert(path):
    raw = path.read_bytes()
    data = tomllib.loads(raw.decode("utf-8"))
    assert data["variant"] == "NT"
    count = len(data["players"])
    assert data["blinds_or_straddles"][2:] == [0] * (count - 2)
    assert len(set(data["antes"])) == 1
    # PHH puts the button last; the playground puts it first.
    order = [count - 1, *range(count - 1)]
    seat = lambda token: order.index(int(token[1:]) - 1)
    holes = [[] for _ in order]
    board, actions = [], []
    street = "preflop"
    for line in data["actions"]:
        tokens = line.split()
        if tokens[:2] == ["d", "dh"]:
            holes[seat(tokens[2])] = [] if "?" in tokens[3] else [tokens[3][:2], tokens[3][2:]]
        elif tokens[:2] == ["d", "db"]:
            board.extend(tokens[2][i:i + 2] for i in range(0, len(tokens[2]), 2))
            street = {3: "flop", 4: "turn", 5: "river"}[len(board)]
        elif tokens[1] == "sm":
            continue
        else:
            action = {"seat": seat(tokens[0]), "street": street, "type": {"f": "fold", "cc": "match", "cbr": "aggress"}[tokens[1]]}
            if tokens[1] == "cbr":
                action["to"] = int(tokens[2])
            actions.append(action)
    classic = path.stem == "dwan-ivey-2009"
    source_path = "data/dwan-ivey-2009.phh" if classic else f"data/pluribus/100/{data['hand']}.phh"
    result = dict(id=path.stem, title="Dwan vs Ivey · 2009" if classic else f"Pluribus · hand {data['hand']}",
                  collection="Classic" if classic else "Pluribus",
                  source=f"https://github.com/uoftcprg/phh-dataset/blob/{REVISION}/{source_path}",
                  sourceSha256=hashlib.sha256(raw).hexdigest(), smallBlind=data["blinds_or_straddles"][0],
                  bigBlind=data["blinds_or_straddles"][1], ante=data["antes"][0],
                  players=[dict(name=data["players"][i], stack=data["starting_stacks"][i], hole=holes[j]) for j, i in enumerate(order)],
                  board=board, actions=actions)
    if classic:
        result["video"] = "https://youtu.be/GnxFohpljqM"
    if "finishing_stacks" in data:
        result["endingStacks"] = [data["finishing_stacks"][i] for i in order]
    return result


if __name__ == "__main__":
    hands = [convert(path) for path in sorted((ROOT / "data/poker-replays/sources").glob("*.phh"))]
    assert len(hands) == 51, f"Expected 51 pinned sources, found {len(hands)}"
    hands.sort(key=lambda hand: (hand["collection"] != "Classic", int(hand["id"].split("-")[-1]) if hand["collection"] != "Classic" else 0))
    output = '// Generated by scripts/build-poker-replays.py. Edit the pinned sources, not this file.\nimport type { ReplayHand } from "./replay";\n\nexport const REPLAY_HANDS: ReplayHand[] = '
    output += json.dumps(hands, ensure_ascii=False, separators=(",", ":")) + ";\n"
    (ROOT / "src/lib/poker/replay-hands.ts").write_text(output, encoding="utf-8")
    print(f"Built {len(hands)} hands, {sum(len(hand['actions']) for hand in hands)} decisions")
